version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server_container_compose
    restart: unless-stopped
    env_file: 
      - .env
    #environment:
      #MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      #MYSQL_DATABASE: ${MYSQL_DATABASE}
      #MYSQL_USER: ${MYSQL_USER}
      #MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_HOST_PORT}:3306"   # expone 3306 del contenedor al puerto del host
    volumes:
      - C:\docker\mysql\data_test:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
