version: "3.9"

services:
  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_3_13_app
    volumes:
      - .:/app
    command: ["python", "app.py"]
    restart: "no"
